language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js

env:
  secure: "s/X5eSzp4eollZzKuNQEURfHxnqBl8kbTfYukmcwAG4EedIfYBFQqgsBEbHGao4wzptXarGdv32Azwu8Bn40XLTcjGui19QWmpV2bMv4Kvlc3cPzzhLE0jtadkvUgMcypxkNFmgQrRN6AgxnmI44aCJg2DzET+C4tnuhBWUf/jto1YEbk3WtcE1qoFIPiyQXDwA9+NOpSCzyF8CY4lMgBaG2Wzvb/W8Lznzuoh33ZEiaO0Q2iQhWjMN86npynmVQehWRSibytcPlThsPdypVjyR5gkJOL/5ZDXWMQvTWDw30EXKJp+5yYbxfN5LA0xar/2chP6Cf5wLKJmFzUrHsp9+KN1WyFfGoxMgc35ZdpE4lIiOJV0lOx1sKBMz5ytcGpCk/9eVgcZBlgI7Jy3cvY9TDwKJmbSIBNYDzbv+wLchoD6fo+wxlzmaCLcausGCnnLIlnTeYhJ8uLmMCkG3Zk/Bhia/nsCDfuxViTBode6OaF0NfxscbEnidi9Xz2hMXOKj7rXdp4p8KY0+Dg+P1D9wPDQ7wpr2G2J6lO44sXv3b/9SkvF3Jg+dYsvFzlE3ohMpX/MGzWwcRfS0gHAJNpk8qnfdmcfSixojBgppA8wI+AqBppMW0Z+qwH7McdNuVXwooYJmZYP7HBcC2CFDRtOo3A1I6q3oKS/APrQmkw/g="
