language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js

env:
  secure: "UFF3fLqRmUCyzRv8BL6x3SzDntVeEcvQ+2Fdh7iZmasUh7AAg0qblWemoE7deOQ8ocpRvpSZatuxXI1ZoUffWF3G+HYz2k7sNOK+Ig6rAIMGHThJIIRNcVSlGdfnCE75V++EUtFDkaMUUIL/VtsKRPkh0V2Ld4NUrWvNKindsKAf2PPoUlffZlA2lG5g+2cFP5Ba4cwSIhFEOD9ANLw6648vN5/CbifraYlXUu2Y3TD/P28/BWlZ7XCbdOhNq8fTe8PHVlw8YFuBFQ7XPLJssnDrysluRPz5f6VbW59PMrmTS6Q6W9GzRug+uC4WKaxUEsXyJIYlioQdgDa3MDxQuzEK1/pKkZZsxJd3ZfPlF+unZoKojt5Hju9NXiDIYf6kgYugY7eBnCbVxP2h5IulNWu/Cip2bUzGBWtJAizMRlt0N2PZQESUptVByLLUbV5qhB7LNdoivD8nPlMwJqFH5bUwGDJvIYUBDND+zV0wVpHt+sDisT9joeXC/H2Dz/Xjm6/DA22V0hnrTE1emfuoqHFTh0YyBQM3M1U0ieJzEvd+3V1Xl71vAAYHYwQJ0KMWWHmZ2kjQz0Vn/HFW7z8+uqpse1tn5HUydGSgDVBhhuYtFL2KUwqeSXAJk8tsQUsRbvKMhK5k1eBKJzsRrHxcnFDrI6qbaNjF6Uvz/8uHyXI="
