language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "rW/9jlJ5B51E3as8F6IPx8cubalCB57T8kjfL+UTlMvzNkWcIe+WK6xADY1cstX4eWBQMOCsTdzHk4yuJLCZF6IJGbvk8U/H/NmBBozGKMxwNM5DGeaEeMIHKjRiBZ0MIcIpMLFWxzsSvR59w2YFXrZ/2CqHxbxZw9qF/6pyuFde74LRHSTOn/hWAaSmCumHE1naqEGF3K4eKLCDXEECJ+l521qGcfrK8wXH9ZuV5P6BMzG8xr93bJzjFZnHUd+vVYgkr01eVPTLc09Yj22Coz1ovnV8HK84JCNasv99G62t7wBxwhQASMluoq3jDsz1M7XOjNJ6OW6wZgyEolJ9DeiUqlHLnwcWl/OEKpU0lzvbZZdtBuzLV8RhMIJioSNXxpqj1+aPPQJtHSHWdOzPETzHVnVu/OtP37j/smna2dZN/zXYGhQr4IEtrZPR6NsiYgsCWJThMMTTfTvf9Bt7KjX5ivnBQnc/VB0vTBThOC+Gwu4ono4ghLRCDDW1ynV7AGY41gCSkfF1iluHDGUWKd4zqOdkDbquv9fM/B/ijxtLy3BGJ+hQvTDjimvGTdynvLAnMFhvxCeZqXqzzzfEbGiEaqfhMyFHC0yuyZV9RKeZ0cuuepGRp36m33xWeO8YICmFFnzADUjomxzf5CWgajDrKTPkScaUvr0Pi5A+vzM="